apiVersion: v1
kind: Service

metadata:
  name: svc-np
  labels:
    bla: bla

spec:
  type: NodePort

  ports:
    - port: 8080
      targetPort: 8383
      nodePort: 32222

  selector:
    app: os-host
