apiVersion: v1
kind: Service

metadata:
  name: my-lb
  labels:
    service: lb

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8383
      nodePort: 31223
  selector:
    app: os-host
